input {
  http {
    host => "0.0.0.0"  # Listen on all available network interfaces
    port => 5044  # Use the desired port
  }
}
filter {
  json {
    source => "message"  # Specify the field containing the JSON data
    target => "api_data" # Specify the field where the extracted data should be stored
  }
}
output {
  elasticsearch {
    hosts => "elasticsearch:9200"  # Elasticsearch container name and port
    index => "msbd"  # Specify the name of the Elasticsearch index
  }
}
